version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5

  - package-ecosystem: "bun"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "web"
    labels:
      - "dependencies"
      - "web"
    open-pull-requests-limit: 10
    groups:
      web-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
